# Site not entirely customized using config
# Some meta tags in _includes/head.html and other file contents need manual edits
title: Nishanth Shanmugham
email: nishanths@utexas.edu
baseurl: ""
url: "https://nishanths.github.io"
github_username: nishanths
comments: false

html_lang: en
permalink: /:title/
exclude: [".sass_cache"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
